export {
  MAX_MARKETS,
  MAX_MARKET_COUNTRIES,
  MAX_MARKET_DOMAINS,
  MarketContextContractError,
  defineMarketCatalog,
  resolveMarket,
  type Market,
  type MarketCatalog,
  type MarketFallback,
  type MarketFallbackReason,
  type MarketResolution,
  type MarketSelector,
  type MarketUnresolvedReason,
} from './domain/market-context';

export {
  MARKET_PUBLICATION_LIMITS,
  MarketPublicationContractError,
  defineMarketPublicationSnapshot,
  defineMarketPublicationPolicy,
  previewMarketPublication,
  type MarketPublicationVariant,
  type MarketPublicationProduct,
  type MarketPublicationSnapshot,
  type MarketPublicationRule,
  type MarketPublicationPolicy,
  type MarketPublicationContext,
  type MarketPublicationState,
  type MarketPublicationProductExclusion,
  type MarketPublicationVariantExclusion,
  type MarketPublicationVariantPreview,
  type MarketPublicationProductPreview,
  type MarketPublicationPreview,
} from './domain/market-publication';
