export {
  MAX_LOCALIZED_EDITIONS,
  LOCALIZED_TEXT_LIMITS,
  LocalizedContentContractError,
  defineLocalizedContent,
  applyLocalizedContentCommand,
  resolveLocalizedContent,
  type LocalizedFields,
  type LocalizedDraft,
  type LocalizedPublishedRevision,
  type LocalizedEdition,
  type LocalizedContent,
  type LocalizedContentCommand,
  type LocalizedTransitionBlockReason,
  type LocalizedContentTransition,
  type LocalizedFallback,
  type StaleTranslationPolicy,
  type LocalizedContentSelection,
  type LocalizedPublicationFreshness,
  type LocalizedUnavailableReason,
  type LocalizedContentResolution,
} from './domain/localized-content';

export {
  MAX_INTERNATIONAL_URLS,
  INTERNATIONAL_HREFLANG_PROFILE,
  InternationalUrlPlanContractError,
  planInternationalUrls,
  type InternationalAlternate,
  type InternationalPage,
  type InternationalUrlExclusion,
  type InternationalUrlPlan,
} from './application/international-url-plan';
