export {
  COMPANY_DIRECTORY_LIMITS,
  CompanyDirectoryContractError,
  defineCompanyDirectory,
  selectCompanyDirectoryEntry,
  type CompanyDirectoryState,
  type CompanyVatDeclaration,
  type Company,
  type CompanySite,
  type CompanyContactIdentityRef,
  type CompanyContact,
  type CompanyRole,
  type CompanyRoleScope,
  type CompanyRoleAssignment,
  type CompanyDirectoryRef,
  type CompanyDirectory,
  type CompanyDirectoryEntry,
  type CompanyDirectoryContractReason,
} from './domain/company-directory';
