export {
  INTEGRATION_DESCRIPTORS,
  INTEGRATION_ERROR_CODES,
  INTEGRATION_HEALTH_STATES,
  INTEGRATION_IDS,
  INTEGRATION_REGISTRY,
  INTEGRATION_STATES,
  IntegrationRegistryError,
  createIntegrationRegistry,
  resolveIntegrationStatuses,
  validateIntegrationRegistry,
  type IntegrationErrorCode,
  type IntegrationEvidence,
  type IntegrationHealthState,
  type IntegrationId,
  type IntegrationOperationEvidence,
  type IntegrationRegistry,
  type IntegrationRegistryIssue,
  type IntegrationSecretPresence,
  type IntegrationState,
  type IntegrationStatus,
  type IntegrationStatuses,
} from './registry';
